sudo: required
dist: trusty
language: c
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install bc
  - sudo apt-get install bmake
addons:
  sonarcloud:
    organization: "suiginsoft-github"
    token:
      secure: "DSDafuEk//kxto6aPJ6JUb0tCephcxjqF9cdfiTvcK12YSY6aa4aOaGe1YGrngXa2bzbG5qE0NGA7k0n/rppqdAxDxu6tokimeG2Nj0jo1Mf33GXfeigTBydv6GIBjXcaHQafBdWd6StY6TJPzwpQwxVn8l8BFCQkvHEv/b/pv2t2TtqnALjQREJ06pRsy+ANcJQJ4DQuFcxNK1cK5cLL9enQfWvMpxGWIF9YRcF+IwGB0PqRkfWZymsn8bYtyyj5/2kfVZB/R2Yo/g/QOQeM1KC8yxiIBKxf7pckQYPi/EVh2yzJZ4CPV57YPec6Tjks466EHhs/HCA7T6DgzLruy4sKHLWpuzq/vRdw7zKtmhk8ScM9VHvS3aC1lB0D/eMaJFsz5aaaGB33xkBi3wSZgw1kzgi4jhc4renY7dVITYq/8UzBwq2q56TaVjPCFMbYh9AtGDJZz7u8uWQYL4nXczOqBkqb0HLNjakNT+17ZUzxjMpt0nx8XBCYSDvI2nD/KRxKVDibP6sjIiMjwkTmc3ZaJK+SBIBQqknpy2srF9sb8b+poZXh5weNmq4Dy66lbUscHBeLIguQS1H3VvhyG9jc191Ltk4LdaN1wYHR7nnwihbxEPSL+MV/53EjtAI8vY7fut0L5FRDGXZUkS3HjO2uLrQPDDooLpwyujnQBc="
script:
  - build-wrapper-linux-x86-64 --out-dir bw-output bmake clean check
  - sonar-scanner -Dsonar.projectKey=hebimath -Dsonar.organization=suiginsoft-github -Dsonar.sources=src -Dsonar.cfamily.build-wrapper-output=bw-output -Dsonar.cfamily.gcov.reportsPath=. -Dsonar.host.url="https://sonarcloud.io"
cache:
  directories:
    - '$HOME/.sonar/cache'
