sudo: required
dist: trusty
language: c
compiler: gcc
before_install:
  - echo "deb http://archive.ubuntu.com/ubuntu xenial main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get build-dep make-dfsg -y
  - sudo apt-get -b source -t xenial make-dfsg -y
script: make && make check
